customhost = "employee.czwwq6pbmbqc.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "Bait3273"
customdb = "employee"
custombucket = "chehzhenyu-employeebucket"
customregion = "us-east-1"
